# render.yaml
services:
  - type: web
    name: flask-arms-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /health
